ALTER TABLE "staff_users"
  ADD COLUMN IF NOT EXISTS "password_changed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "students"
  ADD COLUMN IF NOT EXISTS "password_changed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
